services:
  mq-mysql:
    image: mysql:9.2
    container_name: mediasQuest-db
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mediasQuest-dbdata:/var/lib/mysql
    restart: unless-stopped
    networks:
      - default
      - pma_network

  mq-node:
    image: akuan09/medias-quest:latest
    container_name: mediasQuest-node
    depends_on:
      - mq-mysql
    environment:
      DB_HOST: ${MYSQL_HOST}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      PORT: ${NODE_PORT}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mq-node.rule=Host(`mq-api.asd9.fun`)"
      - "traefik.http.routers.mq-node.tls.certresolver=letsencrypt"
      - "traefik.http.services.mq-node.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik_network"
    networks:
      - default
      - traefik_network

volumes:
  mediasQuest-dbdata:

networks:
  default:
  pma_network:
    external: true
  traefik_network:
    external: true
